## Required mapping. Represents the buildspec version. We recommend that you use 0.2.
version: 0.2

phases:
  ## install: install dependencies you may need for your build
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Nest...
  ## pre_build: final commands to execute before build
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  ## build: actual build commands
  build:
    commands:
      # Build your app
      - echo Build started on `date`
      - echo Compiling the Node.js code


  ## post_build: finishing touches
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - dist/**/*
    - package.json
    - node_modules/**/*
    - .platform/**/*
    - index.html
    - app.js
    - cron.yml
